services:
  serve:
    restart: always
    image: whatwewant/serve:${SERVICE_SERVE_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:${SERVICE_SERVE_PORT}:8080
    environment:
      DIR: /data
    volumes:
      - ${SERVICE_DATA}:/data
      
networks:
  default:
    external: true
    name: compose-ingress
